### ISSUE TITLE
SUGGESTION: Key participant/player information by participant ID

### ISSUE THREAD

**Issue by samhine** [mrtolkien/riot_transmute#1]
Hey,

One of my main pet peeves with the Riot API timeline endpoint is the strange indexing when it comes to `participantFrames`. The documentation states its format is like so `Map[String, MatchParticipantFrameDto]`, but rather than this `String` being `participantId`, it's instead a number that is unrelated. We must reach inside the `MatchParticipantFrameDto` to actually find out which participant frame relates to which participant, when it could be given to us straight away.

Keeping in this theme, where we have a list of players (https://github.com/mrtolkien/riot_api_to_lol_dto/blob/c998ef32b41b7267d956ea2aba7ff73c5a678fad/examples/game_from_match.json#L32, https://github.com/mrtolkien/riot_api_to_lol_dto/blob/c998ef32b41b7267d956ea2aba7ff73c5a678fad/examples/game_from_match_timeline.json#L10), we could instead have a dict which uses participantId as a key. If I'm not mistaken, this would make it much easier when trying to find stats related to a given participant.

The current format of `game_from_match.json` would, given a `participantId`, require us to query like so;
```
participant_info = [info for info in match["teams"]["BLUE"]["players"] where info["id"]==participantId][0]
```
The suggested change would mean we could do;
```
participant_info = match["teams"]["BLUE"]["players"][participantId]
```

Would love to get others' feedback on this, thanks!

**Comment by mrtolkien** [comment]
There are unfortunately many things that make your suggestion hard to apply:
- Players in a game don’t intrinsically have an ID attributed to them
    - The `participantId` field is arbitrary and a poor key
- JSON doesn’t allow integers as keys
- With the new structure, this `id` is only used to link players to kills, deaths, and assists

Overall, this is indeed a poor field, which means using it **more** is the opposite of what we’re trying to achieve. It is also heavily linked to Riot’s API in particular.

A "proper" player key would be the player’s role, but unfortunately those are too hard to properly define and can also be missing.

**Comment by samhine** [comment]
Thanks for the response!

It seems this new `id` field you're applying is synonymous to `participantId` - and would therefore also be arbitary unless I'm misunderstanding.  I guess another option would be to use `accountId` or `summonerName`, but to me it's kind of counter-intuative to have to reach inside an object to find its identifier, rather than just use that identifier as the key.

Also, strings of integers are included numerous times with the Google JSON Style Guide, but I can understand a single 1-10 integers give little information to what may be included within the data itself.

**Comment by mrtolkien** [comment]
> I guess another option would be to use accountId or summonerName, but to me it's kind of counter-intuative to have to reach inside an object to find its identifier, rather than just use that identifier as the key.

Which is exactly why we’re better off without a key, and simply handling them as a list! I don’t see what’s wrong with that when there is no good key.

**Comment by mrtolkien** [comment]
Btw, the data structure discussion is linked to the model module, `lol_dto`. This module is the Riot API data -> `LolGame` DTO function, which is only a small part of the equation.

You can the model module here: https://github.com/mrtolkien/lol_dto

All fields in it are explained and documented, so I will close this thread and new comments can be made in the right repo.
